#ifndef TP3_CONSTANTS_H
#define TP3_CONSTANTS_H

#define X_POS_BEGINNING 0
#define Y_POS_BEGINNING 8
#define X_POS_END 29
#define Y_POS_END 8
#define DEFAULT_LIVES 10
#define MAP_WIDTH 30
#define MAP_HEIGHT 15
#define EMPTY_SQUARE 0
#define INVISIBLE_WALL 1
#define VISIBLE_WALL 2
#define DISCOVERED_WALL 3
#define VISITED_SQUARE 4
#define SQUARE_WIDTH 2 /* How big should a square's width be, in characters */
#define COLOR_EMPTY_SQUARE COLOR_BLACK
#define COLOR_VISIBLE_WALL COLOR_BLUE
#define COLOR_INVISIBLE_WALL COLOR_MAGENTA
#define COLOR_DISCOVERED_WALL COLOR_RED
#define COLOR_PLAYER COLOR_GREEN
#define COLOR_VISITED_SQUARE COLOR_WHITE
#define PAIR_COLOR_PLAYER 3
#define PAIR_COLOR_VISIBLE_WALL 4
#define PAIR_COLOR_INVISIBLE_WALL 5
#define PAIR_COLOR_EMPTY_SQUARE 6
#define PAIR_COLOR_PLUS_SIGN 7
#define PAIR_COLOR_MINUS_SIGN 8
#define PAIR_COLOR_DISCOVERED_WALL 9
#define PAIR_COLOR_VISITED_SQUARE 10
#define BORDER_WIDTH 2
#define BORDER_HEIGHT 2
#define BORDER_STATE_WINDOW_WIDTH 20 * SQUARE_WIDTH + BORDER_WIDTH
#define BORDER_STATE_WINDOW_HEIGHT 8 + BORDER_HEIGHT
#define BORDER_INFORMATION_WINDOW_WIDTH MAP_WIDTH * SQUARE_WIDTH + BORDER_STATE_WINDOW_WIDTH + BORDER_WIDTH
#define BORDER_INFORMATION_WINDOW_HEIGHT 4 + BORDER_HEIGHT
#define BORDER_GAME_WINDOW_WIDTH MAP_WIDTH * SQUARE_WIDTH + BORDER_WIDTH
#define BORDER_GAME_WINDOW_HEIGHT MAP_HEIGHT + BORDER_HEIGHT
#define PLUS_SIGN_POS_X 12
#define PLUS_SIGN_POS_Y 1
#define MINUS_SIGN_POS_X 18
#define MINUS_SIGN_POS_Y 1
#define MAX_FILENAME_LENGTH 256

#endif